  dagster_webserver:
    build:
      context: .
      dockerfile: docker/dagster/Dockerfile
    container_name: de_pipeline_dagster_web
    env_file:
      - .env
    environment:
      DAGSTER_POSTGRES_USER: ${POSTGRES_USER}
      DAGSTER_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DAGSTER_POSTGRES_DB: ${POSTGRES_DB}
      DAGSTER_POSTGRES_HOSTNAME: postgres
      DAGSTER_MEMORY_LIMIT: "1GB"
      DUCKDB_THREADS: ${DUCKDB_THREADS}
      DUCKDB_MEMORY_LIMIT: ${DUCKDB_MEMORY_LIMIT}
      POLARS_MAX_THREADS: ${POLARS_MAX_THREADS}
      DAGSTER_MODULE_NAME: main
    deploy:
      resources:
        limits:
          memory: 1200M
          cpus: '0.8'
    ports:
      - "3000:3000"
    volumes:
      - ./dagster_home:/opt/dagster/dagster_home
      - ./data:/opt/dagster/app/data
      - ./orchestration:/opt/dagster/app/orchestration
      - ./transformation:/opt/dagster/app/transformation
      - ./main.py:/opt/dagster/app/main.py
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - de_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/server_info"]
      interval: 30s
      timeout: 10s
      retries: 3
