version: '3.8'

services:
  # 1. Database (Source)
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: source_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M  # Жесткий лимит памяти!

  # 2. Data Lake
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    deploy:
      resources:
        limits:
          memory: 512M

  # 3. Main ETL Container (Dagster + dbt + Polars)
  dagster_libs:
    build:
      context: .
      dockerfile: docker/dagster/Dockerfile
    container_name: de_project_main
    environment:
      DAGSTER_POSTGRES_USER: user
      DAGSTER_POSTGRES_PASSWORD: password
      DAGSTER_POSTGRES_DB: source_db
      DAGSTER_POSTGRES_HOST: postgres
    volumes:
      - .:/workspaces/de-batch-pipeline # Монтируем весь код внутрь
    depends_on:
      - postgres
      - minio
    command: dagster dev -h 0.0.0.0 -p 3000 -f orchestration/assets/raw_ingest.py # Временная команда заглушка
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          memory: 4G # Основная память тут

volumes:
  postgres_data:
  minio_data:
